version: '3.9'

volumes:
  strapi-db-data: {}
  strapi-upload-data: {}

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  strapi:
    container_name: strapi
    build:
      context: ./cms
      dockerfile: .Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env-compose
    volumes:
      - strapi-upload-data:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    image: postgres:15
    container_name: strapiDB
    restart: unless-stopped
    env_file: .env-compose
    volumes:
      - strapi-db-data:/var/lib/postgresql/data
    networks:
      - strapi


networks:
  strapi:
    driver: bridge